language: java
sudo: false
jdk: oraclejdk8

notifications:
  email: false
  # slack:

branches:
  only:
    - master
    - dev

# jobs:
#   include:
#     - stage: test
#     - stage: inspect

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: $SONARCLOUD_ORGANIZATION
    token: $SONARCLOUD_TOKEN
    # github_token: # in case we want to run sonarscan on pull requests
    branches:
      - master
      - dev
before_install:
  - cd Orderys
  - mvn install:install-file -Dfile=src/lib/ojdbc7.jar -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=12.1.0 -Dpackaging=jar
# install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
# install: true
# before_script:
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mvn test -B
# before_cache:
# after_success:
# after_failure:
# before_deploy:
# deploy:
#   skip_cleanup: true
# after_deploy:
# after_script:

